"""initial schema

Revision ID: 88916a33f702
Revises: 
Create Date: 2026-08-09 10:52:35.397771
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '88916a33f702'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=True),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_request_delay_seconds', sa.Float(), nullable=True),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_stores_slug'), ['slug'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('browser_notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('tracked_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('product_id', sa.String(length=128), nullable=True),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('brand', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lowest_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('highest_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_status', sa.String(length=20), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('price_tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('stock_tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('notify_browser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'url', name='uq_tracked_product_user_url')
    )
    with op.batch_alter_table('tracked_products', schema=None) as batch_op:
        batch_op.create_index('ix_tracked_products_due', ['tracking_enabled', 'last_checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracked_products_last_checked_at'), ['last_checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracked_products_next_check_at'), ['next_check_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracked_products_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracked_products_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracked_products_user_id'), ['user_id'], unique=False)

    op.create_table('monitoring_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('check_status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('adapter', sa.String(length=64), nullable=True),
    sa.Column('layers_used', sa.String(length=255), nullable=True),
    sa.Column('changes_detected', sa.Integer(), nullable=False),
    sa.Column('notifications_created', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tracked_product_id'], ['tracked_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_monitoring_jobs_product_time', ['tracked_product_id', 'started_at'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tracked_product_id'], ['tracked_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('ix_price_history_product_time', ['tracked_product_id', 'recorded_at'], unique=False)

    op.create_table('tracked_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.String(length=191), nullable=False),
    sa.Column('variant_name', sa.String(length=191), nullable=False),
    sa.Column('variant_type', sa.String(length=20), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_watched', sa.Boolean(), nullable=False),
    sa.Column('current_stock', sa.String(length=20), nullable=False),
    sa.Column('previous_stock', sa.String(length=20), nullable=False),
    sa.Column('last_in_stock_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tracked_product_id'], ['tracked_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracked_product_id', 'variant_id', name='uq_variant_per_product')
    )
    with op.batch_alter_table('tracked_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracked_variants_tracked_product_id'), ['tracked_product_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tracked_product_id', sa.Integer(), nullable=False),
    sa.Column('tracked_variant_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('previous_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_error', sa.Text(), nullable=True),
    sa.Column('browser_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tracked_product_id'], ['tracked_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracked_variant_id'], ['tracked_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_dedupe', ['tracked_product_id', 'type', 'created_at'], unique=False)
        batch_op.create_index('ix_notifications_user_time', ['user_id', 'created_at'], unique=False)

    op.create_table('stock_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_variant_id', sa.Integer(), nullable=False),
    sa.Column('stock_status', sa.String(length=20), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tracked_variant_id'], ['tracked_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.create_index('ix_stock_history_variant_time', ['tracked_variant_id', 'recorded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_history_variant_time')

    op.drop_table('stock_history')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_time')
        batch_op.drop_index('ix_notifications_dedupe')

    op.drop_table('notifications')
    with op.batch_alter_table('tracked_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_variants_tracked_product_id'))

    op.drop_table('tracked_variants')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_price_history_product_time')

    op.drop_table('price_history')
    with op.batch_alter_table('monitoring_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_monitoring_jobs_product_time')

    op.drop_table('monitoring_jobs')
    with op.batch_alter_table('tracked_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_products_user_id'))
        batch_op.drop_index(batch_op.f('ix_tracked_products_store_id'))
        batch_op.drop_index(batch_op.f('ix_tracked_products_product_id'))
        batch_op.drop_index(batch_op.f('ix_tracked_products_next_check_at'))
        batch_op.drop_index(batch_op.f('ix_tracked_products_last_checked_at'))
        batch_op.drop_index('ix_tracked_products_due')

    op.drop_table('tracked_products')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_slug'))
        batch_op.drop_index(batch_op.f('ix_stores_domain'))

    op.drop_table('stores')
    # ### end Alembic commands ###
